### ISSUE TITLE
Issue while running

### ISSUE THREAD

**Issue by zxcve** [roxanneluo/Federated-Learning#1]
Hi ,
I keep getting this error:
Traceback (most recent call last):
  File "fl_client.py", line 214, in <module>
    FederatedClient("127.0.0.1", 5000, datasource.Mnist)
  File "fl_client.py", line 92, in __init__
    self.sio.wait()
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\socketIO_client\__init__.py", line 251, in wait
    self._process_packets()
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\socketIO_client\__init__.py", line 278, in _process_packets
    self._process_packet(engineIO_packet)
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\socketIO_client\__init__.py", line 491, in _process_packet
    delegate(parse_socketIO_packet_data(socketIO_packet_data), namespace)
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\socketIO_client\__init__.py", line 513, in _on_event
    namespace._find_packet_callback(event)(*args)
  File "fl_client.py", line 139, in on_request_update
    my_weights, train_loss, train_accuracy = self.local_model.train_one_round()
  File "fl_client.py", line 57, in train_one_round
    validation_data=(self.x_valid, self.y_valid))
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\keras\models.py", line 893, in fit
    initial_epoch=initial_epoch)
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\keras\engine\training.py", line 1555, in fit
    batch_size=batch_size)
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\keras\engine\training.py", line 1413, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\zxcve\Anaconda3\lib\site-packages\keras\engine\training.py", line 142, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected dense_2 to have 2 dimensions, but got array with shape (1200, 1, 10)
disconnect

Do you know fix for this?

**Comment by DockerBB** [comment]
self.x_train = self.x[0:num_train]
        self.x_test = self.x[num_train:num_train + num_test]
        self.x_valid = self.x[num_train + num_test:]
        self.y_train = self.y[0:num_train]
        self.y_train = self.y_train.reshape(self.y_train.shape[0])
        self.y_test = self.y[num_train:num_train + num_test]
        self.y_test = self.y_test.reshape(self.y_test.shape[0])
        self.y_valid = self.y[num_train + num_test:]
        self.y_valid = self.y_valid.reshape(self.y_valid.shape[0])
need reshape
